---
kind: pipeline
type: kubernetes
name: default

steps:
  -
    name: fetch
    image: alpine/git
    when:
      event:
        - push
    commands:
      - git fetch --tags

  -
    name: lint
    image: golang:1.24
    when:
      event:
        - push
    commands:
      - curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/HEAD/install.sh | sh -s -- -b $(go env GOPATH)/bin v2.0.2
      - golangci-lint run ./...

  -
    name: test
    image: golang:1.24
    when:
      event:
        - push
    commands:
      - go test -cover ./...
      - echo -n $(git describe --tags --abbrev=0) > .tags
  
  - 
    name: docker
    image: thegeeklab/drone-docker-buildx
    privileged: true
    settings:
      registry: registry.0x42.in
      username: 
        from_secret: registry_username
      password:
        from_secret: registry_password
      repo: registry.0x42.in/terrence/statesman
      tags: 
        - latest
        - ${DRONE_TAG}
      platforms: 
        - linux/arm64
        - linux/amd64
      when:
        ref:
          - refs/tags/v*.*.*
---
kind: signature
hmac: 96c40eb96631dd2280c526b70bbeda2cb664a914d63d80d3209ef66e7c86bd17

...
